"""Domain entities + message payloads (Pydantic v2)."""

from polynoia.domain.entities import (
    Agent,
    AgentSetup,
    Conversation,
    Pin,
    Provider,
    Server,
    Workspace,
)
from polynoia.domain.messages import (
    ApiPayload,
    AskFormPayload,
    CopyPayload,
    DiffPayload,
    Hunk,
    InlineContent,
    LogsPayload,
    MentionInline,
    Message,
    MessagePayload,
    MetricsPayload,
    SchemaPayload,
    SqlPayload,
    StatusItem,
    SwatchesPayload,
    TaskItem,
    TasksPayload,
    TextBlock,
    TextPayload,
    TextSegment,
    ToolCallPayload,
    TypingPayload,
    WebPayload,
)

__all__ = [
    # entities
    "Agent",
    "AgentSetup",
    "Conversation",
    "Pin",
    "Provider",
    "Server",
    "Workspace",
    # messages
    "ApiPayload",
    "AskFormPayload",
    "CopyPayload",
    "DiffPayload",
    "Hunk",
    "InlineContent",
    "LogsPayload",
    "Message",
    "MessagePayload",
    "MetricsPayload",
    "SchemaPayload",
    "SqlPayload",
    "StatusItem",
    "SwatchesPayload",
    "TaskItem",
    "TasksPayload",
    "TextBlock",
    "TextPayload",
    "TextSegment",
    "MentionInline",
    "ToolCallPayload",
    "TypingPayload",
    "WebPayload",
]
